Repository WordPress/theme-experiments, pull requests merged in 2021-03, with the labels that each got.

#233 Update empty theme to use Gutenberg alignments
  emptytheme/assets/alignments-front.css
  emptytheme/block-templates/singular.html
  emptytheme/experimental-theme.json
  emptytheme/functions.php
Labels: block-based theme

#236 Update TT1 Blocks to use Gutenberg alignments
  tt1-blocks/assets/css/blocks.css
  tt1-blocks/assets/css/style-editor.css
  tt1-blocks/block-template-parts/footer.html
  tt1-blocks/block-templates/404.html
  tt1-blocks/block-templates/index.html
  tt1-blocks/block-templates/page-home.html
  tt1-blocks/block-templates/page.html
  tt1-blocks/block-templates/single.html
  tt1-blocks/experimental-theme.json
  tt1-blocks/functions.php
  tt1-blocks/style.css
Labels: bug

#243 Bump TT1 Blocks to version 4.4.5
  tt1-blocks/readme.txt
  tt1-blocks/style.css
Labels: task
