Repository WordPress/theme-experiments, pull requests merged in 2021-06, with the labels that each got.

#266 TT1 Blocks: Bump the version up to 0.4.7
  tt1-blocks/readme.txt
  tt1-blocks/style.css
Labels: task

#268 Empty Theme: renamed theme.json file
  emptytheme/theme.json
Labels: block-based theme

#267 TT1 Blocks: Make separators 100% wide by default
  tt1-blocks/assets/css/blocks.css
Labels: bug
