Repository WordPress/theme-experiments, pull requests merged in 2021-01, with the labels that each got.

#153 TT1 Blocks: Update separator alignment rules
  tt1-blocks/assets/css/blocks.css
Labels: bug

#149 TT1 Blocks: Clean up for Theme Repo
  tt1-blocks/block-templates/index.html
  tt1-blocks/functions.php
  tt1-blocks/inc/block-patterns.php
  tt1-blocks/inc/block-styles.php
  tt1-blocks/readme.txt
  tt1-blocks/screenshot.png
  tt1-blocks/style.css
Labels: enhancement

#161 Add Armando
  README.md
  armando/README.md
  armando/block-template-parts/comments.html
  armando/block-template-parts/content-single.html
  armando/block-template-parts/footer.html
  armando/block-template-parts/header-three.html
  armando/block-template-parts/header-two.html
  armando/block-template-parts/header.html
  armando/block-template-parts/main-grid.html
  armando/block-template-parts/main.html
  armando/block-template-parts/meta.html
  armando/block-templates/404.html
  armando/block-templates/archive.html
  armando/block-templates/index.html
  armando/block-templates/page.html
  armando/block-templates/search.html
  armando/block-templates/single.html
  armando/classes/class-theme-support.php
  armando/comments.php
  armando/editor-style.css
  armando/experimental-theme.json
  armando/functions.php
  armando/inc/back-compat.php
  armando/inc/block-styles.php
  armando/index.php
  armando/readme.txt
  armando/screenshot.png
  armando/style.css
Labels: block-based theme, needs testing

#168 TT1 Blocks: Version bump + update tags
  tt1-blocks/readme.txt
  tt1-blocks/style.css
Labels: enhancement

#169 TT1 Blocks: Fix short theme description and date.
  tt1-blocks/readme.txt
  tt1-blocks/style.css
Labels: enhancement

#174 TT1 Blocks: Fix frontend full alignment styles
  tt1-blocks/style.css
Labels: bug
